version: "3"

services:
  app:
    image: akrantz01/link-shortener:latest
    ports:
      - 3030:3030
    networks:
      - default
    environment:
      DATABASE_URL=postgres://links:please-change-me@database:5432/postgres
      USER_ID=links
      # PLEASE CHANGE THIS
      PASSWORD=please-change-me

  database:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_USER=links
      # PLEASE CHANGE THIS
      # You also will need to change it on line 11
      POSTGRES_PASSWORD=please-change-me
      POSTGRES_DB=postgres

volumes:
  db-data:
