CREATE TABLE IF NOT EXISTS links (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    link TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    times_used INTEGER NOT NULL DEFAULT 0
);
